### ISSUE TITLE
Ensure adequate coverage of points specific to electron diffraction

### ISSUE THREAD

**Issue by dagewa** [dagewa/DIALS_for_ED_paper#12]
The points listed are:
- Unknown (different) center in each diffraction pattern
- Unknown azimuthal tilt axis position
- "flat" Ewald sphere
- Large uncertainty in the geometrical peak position (excitation error additional to other geometrical errors)
- Often presence of disorder / diffuse scattering in the crystals along the incident beam direction
Each requires a short reply. I think the first three points are adequately covered in the manuscript, or in cited papers. I'll draft replies for each of those here. The final two points are not discussed in depth here so I am not sure what to do with those yet.

**Comment by dagewa** [comment]
@cmaxtb @tgruene Do you have any additional opinion on the above? Thanks, D

**Comment by tgruene** [comment]
- center of diffraction pattern: as far as I know, we do not observe a beam shift with our instruments and our setup. My experience, of course, is limited to 4-5 instruments.
- the 'azimuthal tilt axis position' might refer to the rotation axis? Dials treats this as a vector with arbitrary orientation. We assume initially, it is parallel to the detector plane (z-coordinate = 0 in XDS coords), and the orientation within the plane can be read from the sum of all images. @cmaxtb : do you have an example image, or graph that shows this?
From there, we are back at the refinement of the parameters, because one only needs to be correct within 5-10 degrees. The axis does not change when the detector distance is not change, so one can find the axis per distance setting from a radiation hard sample.
- the flat Ewald sphere only affects the correlation between the parameters during refinement, with the consequence, that the distance is not refined, only the cell (or vice versa, referring to reviewer 2)
- peak positions: We could cite Dimmeler et al, J Appl. Cryst, (2000), 33, 1102-1112 here, one of the older occurrences of 3D protein electron crystallography. However, I believe that profile fitting corrects for variations in the peak positions. I think the variation is the reason why XDS suggest unreasonably large REFLECTING_RANGE value, but I don't know if DIALS has the same issue?
- I have so far ignored diffuse scattering, I guess like most people to in MX and organic crystallography.

**Comment by dagewa** [comment]
Reply composed directly in the draft letter. Closing the issue.
